name: file_saver_ffi
description: "A Flutter plugin for saving files to device storage using FFI and JNI"
version: 0.0.1
homepage:

environment:
  sdk: ^3.10.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
  jni: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  ffigen: ^20.1.1
  jnigen: ^0.15.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true