name: file_saver_ffi
description: "A Flutter plugin for saving files to device storage using FFI and JNI"
version: 0.0.1
homepage: https://github.com/vanvixi/file_saver_ffi.flutter
repository: https://github.com/vanvixi/file_saver_ffi.flutter
issue_tracker: https://github.com/vanvixi/file_saver_ffi.flutter
topics:
  - file-saver
  - file-saver-ffi
  - file-saver-native
  - ffi
  - jni

screenshots:
  - description: "File Saver Ffi"
    path: screenshots/cover.png

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.1.4
  jni: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  ffigen: ^20.1.1
  jnigen: ^0.15.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true